### ISSUE TITLE
Add node info hosted on Tor

### ISSUE THREAD

**Issue by matthewjamesr** [MyHush/myhush.github.io#1]
Tor address: mmphgqdbjvqpazpe.onion

**Comment by leto** [comment]
can we get a vanity name that starts with `hush......onion` ? @matthewjamesr @madbuda 

I feel that it helps with knowing you are clicking on the right .onion link, as well

**Comment by lludlow** [comment]
.onion addresses are normally made of the base32 string of the first 80 bits of the SHA1 hash of the private key of the server.  I am fairly sure with some gpu power I could generate an key that fits a hushxxxxx.onoin

@leto this doesn't guarantee anything, as there is still random characters and there is no clicking, this gets put into hush.conf

But having vanity names makes spoofing easier

**EDIT**
@matthewjamesr  both nodes below are online, bonus http://hushnodexptkgea3.onion/ is our block explorer
```
proxy=127.0.0.1:9050
onlynet=tor
addnode=hushnodejbnzyvfk.onion
addnode=hushnodexptkgea3.onion
```

> No exit node needed to reach these nodes or the block explorer

https://github.com/madbuda/HushOnTor

**Comment by lludlow** [comment]
https://github.com/lachesis/scallion

to generate vanity gpg keys

**Comment by lludlow** [comment]
We should make a way for people to submit nodes as well for tor, it would be nice to have a short list of them

**Comment by radix42** [comment]
maybe a "include TOR nodes" checkbox in the config generator if it doesn't have one already?

**Comment by leto** [comment]
:+1: to an "include Tor nodes" slider like the other options

**Comment by matthewjamesr** [comment]
@radix42 I have a Tor Node option for the config generator already, it will add one Tor node to the config. Can someone compile the "defacto" list of Tor nodes we have and respond with it? After that I will close this issue by adding it to the HUSH readme.

**Comment by leto** [comment]
I would like to see a file in the main hush.git repo that lists known trusted .onion nodes, to make it easy to use in various other projects. I can help with this.

**Comment by matthewjamesr** [comment]
It should be placed in `README.md` under a new section title **Bootstrap Nodes**. With one cat for normal and one for Tor.
