### ISSUE TITLE
myhush.org/supply page showing supply stats

### ISSUE THREAD

**Issue by leto** [MyHush/myhush.github.io#125]
We need an automatically updating page to show investors/miners Hush supply stats.

Most important is to have current supply: https://explorer.myhush.org/api/supply

The % and total zfund amount should also be shown:

```
$ ./hush-cli coinsupply
{
  "result": "success",
  "coin": "HUSH3",
  "height": 172518,
  "supply": 8151849.77026167,
  "zfunds": 181630.33586348,
  "sprout": 0.00000000,
  "total": 8333480.10612515
}
```

**Comment by gilardh** [comment]
@leto Is there an API on https://explorer.myhush.org/ allowing to retrieve the total zfund amount ?

**Comment by leto** [comment]
@gilardh yes, it was https://explorer.myhush.org/api/coinsupply and our https://myhush.org/supply page is live, so I will close this
