### ISSUE TITLE
Remove Whitepaper graphic in mobile

### ISSUE THREAD

**Issue by 128514** [MyHush/myhush.github.io#14]
Whitepaper graphic is sized (with borders?) to handle spacing in desktop. **Its probably better off being hidden in mobile viewports**. It's not a link and is fairly ineffectual in mobile, and would be good to keep mobile as fast and scannable as possible. 

![](https://thumb.gyazo.com/thumb/1200/_dd5e8749781ece49d551ad5056858cee-png.jpg)

**Comment by gilardh** [comment]
The image does not bother me and it is well managed on mobile.
There is one image per section which is uniform.

![screenshot_20180903-101452_chrome](https://user-images.githubusercontent.com/39105646/44978657-8c990480-af6b-11e8-9be7-105882e23dcc.jpg)

I propose to keep this picture and close this 'issue'.

**Comment by gilardh** [comment]
@leto I propose to keep this picture and close this 'issue'.
