### ISSUE TITLE
Make /youtube redirect

### ISSUE THREAD

**Issue by leto** [MyHush/myhush.github.io#145]
yep

**Comment by leto** [comment]
https://www.youtube.com/channel/UCn7ED82Rr1qls6kS8k9YgPg

**Comment by leto** [comment]
donezo

https://myhush.org/youtube?zec=milktoast

**Comment by gilardh** [comment]
You were faster than me. @leto 🥇

**Comment by leto** [comment]
https://hush.is/youtube is the preferred link

**Comment by gilardh** [comment]
This is not possible at the moment, we don't have the domain name hush.is ?
