### ISSUE TITLE
Funny 404 Page

### ISSUE THREAD

**Issue by leto** [MyHush/myhush.github.io#150]
We need one, with a custom funny Hush-themed graphic

**Comment by leto** [comment]
250 HUSH bounty for doing a new graphic and updating our website via Github. This bounty can be shared.

**Comment by leto** [comment]
Example: https://www.reddit.com/borkenlinkslulz

**Comment by leto** [comment]
Above link shows various funny images if you reload

**Comment by csharpee** [comment]
Gosh, if this was equivalent to ratios of 1:1; a nice unique creation costs a lot; esp. with A.I. procedural designs. Freelance unevenness will become more costly and A.I. will become more inexpensive to use for common creative folks. If we predict 8yrs for Hush greatness, we may be thinking $2,500.. but, we got to think now, which is 2,500 hush for a great unique awesome sauce the universe has never seen before.

**Comment by gilardh** [comment]
These aren't really funny images but it's a good step.

We have to put images in the 'images/404/' folder then add the images in the table (var images = ['404-1.png', '404-2.png', '404-3.png', '404-4.png', '404-5.png'];) of the 404.html file for add or change images.

https://github.com/MyHush/myhush.github.io/pull/157

**Comment by gilardh** [comment]
I recommend size images between 640x400 and 800 x 480 in png or jpg

**Comment by gilardh** [comment]
https://github.com/MyHush/myhush.github.io/pull/158

I add aledel and Mistletoe image.

**Comment by leto** [comment]
@gilardh I think this solves it, we have a custom 404 now
