### ISSUE TITLE
Website Improvements & Concerns

### ISSUE THREAD

**Issue by oDinZu** [MyHush/myhush.github.io#33]
@matthewjamesr 
-Who has the key to the domain?
-Can I have the vuejs build files to make changes to the website?

**Firefox Testing Desktop/Mobile**
-Navbar About & Language menu dropdown left align **[Completed by Hush Team]**
-Discord link needs updated **[Completed by Hush Team]**
-Update Team section **[Completed by Hush Team]**
-Images for team need to be more responsive and flow better for > 768px. 
-Mobile view GET STARTED button needs more spacing. **[Completed by Hush Team]**
-Mobile/Desktop view whitepaper png needs a link to the whitepaper if we are going to keep it. (All mobile images need to be visible or linked or removed on mobile view. Tough to see and decode the image. 
-Mobile text align for justify needs to be center aligned or left aligned **[Completed by Hush Team]**
-Be nice if content flowed around images once mobile view.
-The transition effect for navbar needs to be faster before it reaches "Hush- Speak and Transact Freely" **[Completed by Hush Team]**
-Testnet Explorer & Web Wallet Links needed updated or removed. If we do not have an official secure web wallet we can trust, we should remove it from the Tools. **[Completed by Hush Team]**

Overall, beautiful single page web page and cool technology, simply some small and important changes needed to be done. To make changes, the vuejs build files will be helpful for me.

**Comment by gilardh** [comment]
All the evolutions have been made.
Could you close this 'issue'?
