### ISSUE TITLE
What "https://hush.lucky-mining.com.ua" dead ?

### ISSUE THREAD

**Issue by OleksandrBlack** [MyHush/myhush.github.io#40]
@joshgentry @leto in https://github.com/MyHush/myhush.github.io/commit/edbf1cb8073f119f9d52d8016d1323de382e7e71
I want to clarify. For what reasons did the pool "https://hush.lucky-mining.com.ua" be considered dead?
**Home page** - lucky-mining.com.ua
**Link pool** - https://hush.lucky-mining.com.ua
**Block Statistics** -  https://hush.lucky-mining.com.ua/index.php?page=statistics&action=blocks
**Afflicts this attitude (**

**Comment by joshgentry** [comment]
@OleksandrBlack sorry if this was done in mistake, but the page located at this URL: https://hush.lucky-mining.com.ua/

Returns this content:
```
<html><head><title>502 Bad Gateway</title><style></style></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>


<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
</body></html>
```

I see that the [block stats page](https://hush.lucky-mining.com.ua/index.php?page=statistics&action=blocks) loads correctly.

I can re-add Lucky Mining with the second URL, or would you like to try to debug why the first doesn't load?

**Comment by joshgentry** [comment]
@OleksandrBlack just noticed that this page-load issue has been corrected on your end and re-added Lucky Mining to the pools section in commit c438013.

Sorry about the overly hasty ✂️!
