### ISSUE TITLE
Add info about using Hush with Agama

### ISSUE THREAD

**Issue by leto** [MyHush/myhush.github.io#58]
We need a dedicated page on myhush.org about how to use Hush with desktop and mobile agama, with these links:

https://support.komodoplatform.com/support/solutions/articles/29000024423-activate-advanced-features

https://play.google.com/store/apps/details?id=com.supernet.agama

100 Hush bounty for making this page + adding a link to it from the main page/etc

**Comment by gilardh** [comment]
It's done!

![20190215 hush in agama](https://user-images.githubusercontent.com/39105646/52882748-f5b2b400-3168-11e9-9865-277b98944bc5.jpg)

**Comment by leto** [comment]
@gilardh awesome work, thanks!
