### ISSUE TITLE
Team Member Names

### ISSUE THREAD

**Issue by UrgeyBergy** [MyHush/myhush.github.io#95]
If we’re using anonymous icons and whatnot, I’d like my name to be changed to ‘Berg’ 
Not sure how DukeLeto feels about his name.

**Comment by leto** [comment]
Everybody is free to use any name or picture they want (within reason). I would like the image below and "Duke Leto" as my name

![god_emperor](https://user-images.githubusercontent.com/30298/65380831-f9775d80-dc98-11e9-939b-63a97cf6ce44.png)

**Comment by leto** [comment]
@UrgeyBergy i just updated your name :+1:

**Comment by gilardh** [comment]
@leto Can you send me a picture of better quality so that I can see your picture bigger?
![image](https://user-images.githubusercontent.com/39105646/65393549-5569e100-dd82-11e9-890f-bb85e671aea8.png)

**Comment by gilardh** [comment]
![20190924 Duke](https://user-images.githubusercontent.com/39105646/65514492-b0641b00-dedd-11e9-910b-9af8a28feebc.png)

**Comment by gilardh** [comment]
@leto Update completed.
We should be able to close this issue.

![image](https://user-images.githubusercontent.com/39105646/65546258-71eb5200-df17-11e9-9b32-402f55e64a85.png)
